export const URLS = {
  login: "/api/v1/student/login/",
  register: "api/v1/auth/teacher/register/",
  teacherProfile: "/api/v1/auth/teacher/profile/",
  // olimpiadaQuizList: "/api/v1/quiz/sciences/list/",
  // quizTest: "/api/v1/quiz/quizzes/",
  // submitAnswers: "/api/v1/quiz/submit-quiz-result/",
  // recieveCode: "/api/v1/student/verify-sms/",
  // resultQuiz: "/api/v1/quiz/result/list/",
  resendSMSCode: "/api/v1/student/resend-sms-code/",
  forgetPassword: "/api/v1/auth/student/forgot-password/",
  newPassword: "api/v1/auth/student/reset-password/",
  registerDate: "/api/v1/student/register_date/",
  resendSMSCodeForget: "/api/v1/auth/student/verify-sms-code/",
  faqs: "/faqs/",
  networkings: "/networking/",
  documents: "/olimpiada-about/",
  ofertas: "/nizom/",
  banner: "/banner/",
  beforeReminder: "/before_test_reminder/",
  afterReminder: "/after_test_reminder/",
  schoolClasses: "api/v1/auth/class/class_name_listview/",
  studentSubjects: "/api/v1/func_student/my-subjects/",
  teacherSubjects: "/api/v1/func_teacher/my-subjects/",
  chapters: "/api/v1/func_teacher/my-chapters/list/",
  createChapter: "/api/v1/func_teacher/my-chapters/create/",
  topics: "/api/v1/func_teacher/my-topics/list/",
};
